import { FontAwesome } from '@expo/vector-icons';
import { useExplorer } from '@projectmirror/shared';
import React, { useState } from 'react';
import {
  SafeAreaView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';

export interface TutorialCarouselProps {
  onFinish: (didView: boolean) => void;
  showSkip?: boolean;
}

interface Slide {
  icon: React.ComponentProps<typeof FontAwesome>['name'];
  iconColor: string;
  title: (explorerLabel: string) => string;
  body: (explorerLabel: string) => string;
}

const SLIDES: Slide[] = [
  {
    icon: 'film',
    iconColor: '#2e78b7',
    title: (explorerLabel) => `A Private Stage, Just for ${explorerLabel}`,
    body: (explorerLabel) =>
      `Every Reflection goes directly to ${explorerLabel} — no algorithm, no noise. It lands on their screen, waiting for them to choose when to watch. When they do, you may receive a Selfie captured at that exact moment!`,
  },
  {
    icon: 'microphone',
    iconColor: '#fcd34d',
    title: () => 'Set the Stage',
    body: (explorerLabel) =>
      `Every Reflection arrives with context — your own recorded voice or an AI-generated caption, plus a Rich Narration generated by AI that describes the moment in detail. The more context you share with the AI, the richer ${explorerLabel}'s experience.`,
  },
  {
    icon: 'paper-plane',
    iconColor: '#4ade80',
    title: () => 'Ready to Begin',
    body: () =>
      `Tap the + button to choose the kind of Reflection you want to send. If you ever need help along the way, look for the "How it works" link on the creation screen.`,
  },
];

export function TutorialCarousel({ onFinish, showSkip }: TutorialCarouselProps) {
  const { explorerName } = useExplorer();
  const [currentSlide, setCurrentSlide] = useState(0);

  const explorerLabel = explorerName || 'the Explorer';
  const slide = SLIDES[currentSlide];
  const isLast = currentSlide === SLIDES.length - 1;

  const handleNext = () => {
    if (isLast) {
      onFinish(true);
    } else {
      setCurrentSlide((prev) => prev + 1);
    }
  };

  return (
    <SafeAreaView style={styles.safe}>
      <View style={styles.container}>
        {/* Exit button — always visible */}
        <TouchableOpacity
          style={styles.skipButton}
          onPress={() => onFinish(false)}
          activeOpacity={0.7}
        >
          <Text style={styles.skipText}>{showSkip ? 'Done' : 'Skip'}</Text>
        </TouchableOpacity>

        {/* Slide content */}
        <View style={styles.slideContent}>
          <View style={[styles.iconCircle, { backgroundColor: `${slide.iconColor}22` }]}>
            <FontAwesome name={slide.icon} size={52} color={slide.iconColor} />
          </View>

          <Text style={styles.slideTitle}>{slide.title(explorerLabel)}</Text>
          <Text style={styles.slideBody}>{slide.body(explorerLabel)}</Text>
        </View>

        {/* Progress dots */}
        <View style={styles.dotsRow}>
          {SLIDES.map((_, i) => (
            <View key={i} style={[styles.dot, i === currentSlide && styles.dotActive]} />
          ))}
        </View>

        {/* Next / Let's Go */}
        <TouchableOpacity
          style={styles.nextButton}
          onPress={handleNext}
          activeOpacity={0.85}
        >
          <Text style={styles.nextButtonText}>{isLast ? "Let's Go!" : 'Next'}</Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#121212',
  },
  container: {
    flex: 1,
    paddingHorizontal: 28,
    paddingBottom: 36,
    justifyContent: 'space-between',
  },
  skipButton: {
    alignSelf: 'flex-end',
    paddingTop: 16,
    paddingBottom: 8,
  },
  skipText: {
    color: '#888',
    fontSize: 15,
    fontWeight: '500',
  },
  slideContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
  },
  iconCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  slideTitle: {
    fontSize: 26,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
  },
  slideBody: {
    fontSize: 16,
    color: '#aaa',
    lineHeight: 25,
    textAlign: 'center',
    maxWidth: 320,
  },
  dotsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 24,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#333',
  },
  dotActive: {
    backgroundColor: '#2e78b7',
    width: 20,
  },
  nextButton: {
    backgroundColor: '#2e78b7',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  nextButtonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '700',
  },
});
